<?$i = 1;$count = 0;?>
<!--FOR PHOTO CHOOSER-->
<form method="post" action="" class="clearfix"  enctype="multipart/form-data" >
	<div id="editorContainer">
		<!--XML NODES!-->
	<?foreach($this->_get('array_of_xml') as $node):?>
		<?if($node['name'] !== 'data' && $node['tag'] != 'END'):?>
			<!--IF NODE IS AN IMAGE-->
			<?if($node['name'] === 'image_id'):$count++;?>
				<div class="clearfix mVxl row image_group" id="node_<?=$i?>">
					<div class="col-xs-2">
						<span class="element_description">Image</span>
					</div>
					<div class="col-xs-10 clearfix">
						<div class="image_holder fleft mRl">
							<div id="image_overflow">
								<div id="img" style="background-image:url(<?='http://'.$_SERVER['SERVER_NAME'].'/'.PHOTO_LIBRARY_DIRECTORY.'/'.$node['image_path']?>)"></div>
							</div>
						</div>
						<input class="image_id" type="hidden" name="<?=$i?>" value="<?=$node['value']?>"> 
						<span class="show_photo_chooser pointer fleft posAbs btn" id="node_<?=$i?>">CHANGE IMAGE</span>
						<span class="remove_photo pointer fleft posAbs btn">REMOVE IMAGE</span>
					</div>
				</div>
				<?$i++;?>
			<?elseif($node['name'] === 'image'):?>
				<div class="clearfix mVxl row image_group" id="node_<?=$i?>">
					<div class="col-xs-2">
						<span class="element_description">Image</span>
					</div>
					<div class="col-xs-10 clearfix">
						<div class="image_holder fleft mRl">
							<div id="image_overflow">
								<div id="img" style="background-image:url(<?='http://'.$_SERVER['SERVER_NAME'].'/'.PHOTO_LIBRARY_DIRECTORY.'/'.$node['image_path']?>)"></div>
							</div>
						</div>
						<input class="image_id" type="hidden" name="<?=$i?>_image" value="<?=$node['attributes']['id']?>"> 
						<span class="show_photo_chooser pointer fleft posAbs btn" id="node_<?=$i?>">CHANGE IMAGE</span>
						<span class="remove_photo pointer fleft posAbs btn">REMOVE IMAGE</span>
					</div>
				</div>
				<?$i++;?>
			<?elseif($node['name'] === 'attachment'):?>
				<div class="clearfix mVxl row" id="node_<?=$i?>">
					<div class="col-xs-2">
						<span class="element_description">Attachment </span>
					</div>
					<div class="col-xs-10 clearfix">
						<div class="mLxxls mTs">
							<div class="clearfix mBs" id="file_upload">
								<?php if(file_exists('Data/Attachments/'.$node['attributes']['hash_file_name'])) : ?>
									<!-- means there is existing file -->
									<input type="hidden" name="attachment_checker_<?=$i?>" value="
										<?php echo htmlspecialchars(json_encode(
											array(
												"name"=>$node['attributes']['name'],
												"hash_file_name"=>$node['attributes']['hash_file_name'],
												"mime_type"=>$node['attributes']['mime_type']
											)
									)); ?>"/>
								<?php else : ?>
									<!-- means there is no existing file or the user replaced the file; -->
									<input type="hidden" name="attachment_checker_<?=$i?>" value="0"/>
								<?php endif; ?>
						        <input id="faux" type="text" value="<?php echo $node['attributes']['name']; ?>"/>
							    <a class="pointer browseAtt" id="browse">BROWSE</a>
							    <div id="wrapper" class="pointer">
							        <input id="input" type="file" name="<?=$i?>_attachment" size="1" />
							    </div>
							</div>
						</div>
					</div>
				</div>
				<?$i++;?>
			<?else:$count = 0;?>
				<div class="clearfix mVxl row">
					<?$clean_description = array('_','editor')?>
						<span class="element_description col-xs-2"><?=str_replace($clean_description, ' ', $node['name'])?></span>
					<?if($node['value'] !== ''):?>
						<div class="element_content col-xs-10">
						<? if(!preg_match('/editor/i', $node['name'])):?>
							<input type="text" class=" pHs w100 expand25-250" name="<?=$i?>"
								value="<?=$node['value']?>" />
						<?else:?>
							<textarea id="<?=$node['name'] ?>" class="editor" name="<?=$i?>">
								<?=$node['value']?>
							</textarea>
						<?endif;?>
						</div>
					<?$i++;?>
					<?endif;?>
				</div>
			<?endif;?>
		<?endif;?>
	<?endforeach;?>
	</div>
	<div class="clearfix mVxl row">
		<div class="col-xs-2 col-xs-offset-10">
			<input class=" mAl btn" type="submit" name="save" value="save" />
		</div>
	</div>
</form>

<div class="popupDialog imageId_error hide">
	<span class="deleteText fc_starfish_gray8 fwB"><span
		class="fc_starfish_red">ERROR</span> retrieving albums, check
		image_id.</span>
	<div id="button_container">
		<span class="btn pointer mTs closeDialog" title="check XML file">OK</span>
	</div>
</div>
