<?php $lcd = $this->data["lcd"];?>


<nav class="navbar navbar-inverse navbar-static-top header blackGradient" role="navigation">
        <div class="container">
        <!-- Stack the columns on mobile by making one full-width and the other half-width -->
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 top">
	              <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <a class="navbar-brand pull-left" href="/">
	                	<img src="/Project/1_Website/Design/Panels/header/images/clefsdor-logo.png" class="img-responsive">
	               	</a>
	              </div>
	              <div class="pull-right mTxxl">
	              	<form class="navbar-form" role="search">
				        <div class="input-group">
				            <input type="text" class="form-control" placeholder="SEARCH" name="srch-term" id="srch-term">
				            <div class="input-group-btn">
				                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				            </div>
				        </div>
				    </form>
	              </div>
	        </div> 
	    </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="100 mTs">
            <div class="collapse navbar-collapse container" id="bs-example-navbar-collapse-1">
            
         
               <ul class="nav navbar-nav container">
                    <li>
                        <a class="page-scroll" href="/">HOME</a>
                    </li>
                    <li class="dropdown aboutUs">
			          <a href="/about" class="dropdown-toggle page-scroll " data-toggle="dropdown" id="dropdownMenu1" aria-expanded="true">ABOUT US</a>
			          <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu1">
			            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent">
			            		<li>
			            			<a href="/about/history">Les Clefs d'Or Philippines</a>
			            		</li>
			            		<li>
			            			<a href="/about/message">Message from the President</a>
			            		</li>
			            		<li>
			            			<a href="/about/committee">Executive Committee</a>
			            		</li>
			            		<li>
			            			<a href="/about/constitution">Constitution and By-Laws</a>
			            		</li>
			            		<li>
			            			<a href="/about/events">Upcoming Events</a>
			            		</li>
			            	</ul>
			            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent">
			            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5">
			            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg">
			            	</div>
			            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7">
			            		<h1><a href="#">Peninsula</a></h1>
			            		<hr>
			            		<div class="ellipsis">
			            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
			            		</div>
			            	</div>
			            </div>
			          </div>
			        </li>
                    <li class="dropdown members">
                        <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" id="dropdownMenu2" aria-expanded="true">MEMBERS</a>
                        <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu2">
				            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent">
				            		<li>
				            			<a href="/members">Full Members</a>
				            		</li>
				            		<li>
				            			<a href="/members/adherent">Adherent Members</a>
				            		</li>
				            		<li>
				            			<a href="/members/membership">Membership</a>
				            		</li>
				            	</ul>
				            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent">
				            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5">
				            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg">
				            	</div>
				            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7">
				            		<h1><a href="#">Peninsula</a></h1>
				            		<hr>
				            		<div class="ellipsis">
				            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
				            		</div>
				            	</div>
				            </div>
			          </div>
                    </li>
                    <li class="dropdown clefs">
                    	<a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" id="dropdownMenu3" aria-expanded="true">LES CLEFS D'OR</a>
                        <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu3">
				            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent">
				            		<li>
				            			<a href="/les-clefs-dor">UICH</a>
				            		</li>
				            		<li>
				            			<a href="<?php echo $lcd->uich_website_link;?>">UICH Website Link</a>
				            		</li>
				            		<li>
				            			<a href="<?php echo $lcd->revue_website_link;?>">Revue</a>
				            		</li>
				            	</ul>
				            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent">
				            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5">
				            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg">
				            	</div>
				            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7">
				            		<h1><a href="#">Peninsula</a></h1>
				            		<hr>
				            		<div class="ellipsis">
				            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
				            		</div>
				            	</div>
				            </div>
			          </div>
                    </li>
                    <li>
                        <a class="page-scroll" href="/hotels">HOTELS</a>
                    </li>
                    <li class="dropdown guide">
                        <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" id="dropdownMenu4" aria-expanded="true">CITY GUIDE</a>
                        <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu4">
				            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent">
				            		<li>
				            			<a href="#">Eat</a>
				            		</li>
				            		<li>
				            			<a href="#">Play</a>
				            		</li>
				            		<li>
				            			<a href="#">Stay</a>
				            		</li>
				            	</ul>
				            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent">
				            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5">
				            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg">
				            	</div>
				            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7">
				            		<h1><a href="#">Peninsula</a></h1>
				            		<hr>
				            		<div class="ellipsis">
				            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
				            		</div>
				            	</div>
				            </div>
			          </div>
                    </li>
                    <li class="dropdown press">
                        <a href="#" class="dropdown-toggle page-scroll" data-toggle="dropdown" id="dropdownMenu5" aria-expanded="true">PRESS ROOM</a>
                        <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu5">
				            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent">
				            		<li>
				            			<a href="#">Features</a>
				            		</li>
				            		<li>
				            			<a href="#">Press Releases</a>
				            		</li>
				            	</ul>
				            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent">
				            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5">
				            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg">
				            	</div>
				            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7">
				            		<h1><a href="#">Peninsula</a></h1>
				            		<hr>
				            		<div class="ellipsis">
				            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
				            		</div>
				            	</div>
				            </div>
			          </div>
                    </li>
                    <li class="dropdown contact">
                    	<a class="page-scroll" href="/contact">CONTACT US</a>
<!--                         <a href="/" class="dropdown-toggle page-scroll" data-toggle="dropdown" id="dropdownMenu6" aria-expanded="true">CONTACT US</a> -->
<!--                         <div class="dropdown-menu container mAuto" role="menu" aria-labelledby="dropdownMenu6"> -->
<!-- 				            	<ul class="dropDownColor col-lg-4 col-md-4 col-sm-12 col-xs-12 leftContent"> -->
<!-- 				            		<li> -->
<!-- 				            			<a href="/option">Message Option</a> -->
<!-- 				            		</li> -->
<!-- 				            		<li> -->
<!-- 				            			<a href="#">Address and Contact Details of Les Clefs d'Or</a> -->
<!-- 				            		</li> -->
<!-- 				            	</ul> -->
<!-- 				            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 rightContent"> -->
<!-- 				            	<div class="imgContainer col-lg-5 col-md-5 col-sm-5 col-xs-5"> -->
<!-- 				            		<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel.jpg"> -->
<!-- 				            	</div> -->
<!-- 				            	<div class="descContainer col-lg-7 col-md-7 col-sm-7 col-xs-7"> -->
<!-- 				            		<h1><a href="#">Peninsula</a></h1> -->
<!-- 				            		<hr> -->
<!-- 				            		<div class="ellipsis"> -->
<!-- 				            			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p> -->
<!-- 				            		</div> -->
<!-- 				            	</div> -->
<!-- 				            </div> -->
<!-- 			          </div> -->
                    </li>

                </ul>
            </div>
       	</div>
            <!-- /.navbar-collapse --
        </div><!-- /.container -->     
</nav>