<img src="/Data/Images/<?php echo $this->_XMLObj->play->image[0]->path?>" >
<img src="/Data/Images/<?php echo $this->_XMLObj->eat->image[0]->path?>" >
<img src="/Data/Images/<?php echo $this->_XMLObj->stay->image[0]->path?>" >

<h1>Eat</h1>
<?php echo $this->displayElement("page_content_editor", 0);?>

<br />

<h1>Play</h1>
<?php echo $this->displayElement("page_content_editor", 1);?>

<br />

<h1>Stay</h1>
<?php echo $this->displayElement("page_content_editor", 2);?>

