
<!-- 	process applciation -->
	<div class="popupDialog processing gradient hide MyriadPro">
		<p>Please wait while we are processing your information.</p>
			
		<p>Step 1: Personal Information</p><span id="step_1" class="load"></span>
		<p>Step 2: Documents and Certificates</p><span id="step_2" class=""></span>
		<p>Step 3: Skills / Experience</p><span id="step_3" class=""></span>
	</div>
<!-- 	error message -->
	<div class="popupDialog popError gradient hide MyriadPro">
		<span class="exclamation mRs mBm"></span><h3 class="ffArvil">Error</h3>
		<p>The information you have provided is incomplete or wrong. 
		Please go back and fill up the required fields. </p>
		<span class="btnBack"></span>
	</div>
	
