<!--**************************************
				SCRIPT LINKS
    **************************************-->
<script src="Project/1_Website/Design/Main_Layout/scripts/global_javascript.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/plugins/Validation/javascript/validation.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/plugins/bootstrap/javascript/bootstrap.min.js" type="text/javascript"></script>
<script src="Project/1_Website/Design/Main_Layout/plugins/jquery.dotdotdot/javascript/jquery.dotdotdot.min.js" type="text/javascript"></script>
<script type="text/javascript" src="Project/1_Website/Design/Main_Layout/plugins/jquery.bxslider/javascript/jquery.bxslider.min.js"></script> 
<script type="text/javascript" src="Project/1_Website/Design/Main_Layout/plugins/mCustomScrollbar/javascript/jquery.mCustomScrollbar.concat.min.js"></script> 

