<div class="jumbotron" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/backgrounds/about-us-banner.jpg')">
</div>

<div class="aboutContainer blackGradient">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12">EXECUTIVE COMMITTEE</h1>
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class="pTxxl">
				<div class="slider1">
				
					<?php foreach($this->members as $member):?>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="<?php echo $member["image_path"]?>">
				  	<div class="card_content">
					   <h2><?php echo $member["article_title"]?></h2>
					   <p><?php echo $member["content"]?></p>
					   <div class="text-center">
					   	<a href="/members/view/<?php echo $member["permalink"]?>" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <?php endforeach?>
				  
				</div>
		</div>
	</section>
</div>
