<div class="jumbotron" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/backgrounds/about-us-banner.jpg')">
</div>

<div class="aboutContainer blackGradient">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12">CONSTITUTION AND BY-LAWS</h1>
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class="pTxxl">
			<ul>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
				<li>
					<p>Lorem Ipsum Brown Fox</p>
				</li>
			</ul>
		</div>
	</section>
</div>