<div class="jumbotron" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/backgrounds/about-us-banner.jpg')">
</div>

<div class="aboutContainer blackGradient">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12">UPCOMING EVENTS</h1>
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class="pTxxl">
				<div class="slider1">
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   <div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/member-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewEvent"></a>
					   </div>
					</div>
				  </div>
				</div>
		</div>
	</section>
</div>
