<div class="jumbotron" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/backgrounds/about-us-banner.jpg')">
</div>

<div class="aboutContainer blackGradient">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12">MESSAGE FROM THE PRESIDENT</h1>
				<hr class="col-lg-3 col-md-3 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class="col-lg-10 col-lg-offset-1 pTxxl">
				<p>Officially registered as <a href="/">U.I.C.H (Union Internationale des Concierge d'H&ocirc;tels)</a>. Les Clefs d'Or is an international network of men and women with common interests and goals. They have their own mystique, a combination of their expertise sources of inside information, intelligence and communication.</p>
				<div class="pTxl">
					<p>
						On the first day of a seminar in Singapore, Manny Suarez and Claire Cuadrado were introduced as delegates from 
						the Philippines &ndash; and they didn&rsquo;t even know each other!
						<br><br>
						That is how Les Clefs d'Or Philippines started.  
						The seminar was entitled, "A Seminar on the World's Least Known Profession."  Held through the auspices 
						of Les Clefs d'Or Singapore, the seminar opened their eyes to the world of conciergerie.  On their first day 
						back at work in Manila, they started to compare notes and focused on how to form a local association of concierges.
						<br><br>
						Except for the 5 star hotels in Manila, no one knew what Concierge is all about.  Meetings after meetings, 
						members started to join Manny and Claire.  Amongst the first to come in were; Jobel Ramos of the Hotel Nikko 
						Manila Garden, Robbie Gonzales of The Manila Peninsula, Marc Bernie Corpus of The Mandarin Oriental, 
						Marie Zulueta of Hotel Inter-Continental Manila, Rorie Ylagan of then The Westin Philippine Plaza, Vic Cruz, 
						Roland Diokno, Gina Rivera and Gana of The Manila Hotel and Andy Pongco of then Manila Midtown Ramada Hotel.  
						Thus saw the birth of the "Concierge and Guest Services Association of the Philippines", 
						with the logo resembling very much that of a Swiss bank.
					</p>
				</div>
		</div>
	</section>
</div>