<div class="container pTm">
		<section class="row pBl firstRow">
			<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 concierge pBm">
				<div class="carousel slide" data-ride="carousel">
				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <div class="item active">
				    	<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 concierge pBm">
					      <h1>CONCEIRGE RECOMMEND</h1>
						  <h2>Antonio&rsquo;s Restaurant</h2>
						  <h3>Title : Antonio&rsquo;s Named as one of the Asia&rsquo;s Best</h3>
						  <div class="shortDesc pTm">
							<p>Antonio&rsquo;s made it to the list of 
										Asia&rsquo;s 50 Best Restauant 2015.
								 		<br><br>
										The famed Tagaytay restaurant 
										featuing elegant and delectable 
										served in a polished and cozy 
										setting ranks forty eight on the list. 
										The only restaurant in the country
										that made it to the prestigious 
										awards.</p>
						  </div>
						 </div>
						 <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 imgContainer">
							<img class="img-responsive posRel" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel-1.jpg">
							<img class="img-responsive overlay posAbs overlay" src="/Project/1_Website/Design/Main_Layout/images/other/overlay.png">
						</div>
				    </div>
				    <div class="item">
					    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 concierge pBm">
					      <h1>CONCEIRGE RECOMMEND</h1>
						  <h2>Antonio&rsquo;s Restaurant</h2>
						  <h3>Title : Antonio&rsquo;s Named as one of the Asia&rsquo;s Best</h3>
						  <div class="shortDesc pTm">
							<p>Antonio&rsquo;s made it to the list of 
										Asia&rsquo;s 50 Best Restauant 2015.
								 		<br><br>
										The famed Tagaytay restaurant 
										featuing elegant and delectable 
										served in a polished and cozy 
										setting ranks forty eight on the list. 
										The only restaurant in the country
										that made it to the prestigious 
										awards.</p>
						  </div>
						 </div>
						 <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 imgContainer">
							<img class="img-responsive posRel" src="/Project/1_Website/Design/Main_Layout/images/other/sample-hotel-1.jpg">
							<img class="img-responsive overlay posAbs overlay" src="/Project/1_Website/Design/Main_Layout/images/other/overlay.png">
						</div>
				    </div>
				  </div>
				</div>
			</div>
			<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 featuredMember pBm">
				<div class="carousel-fade carousel slide" data-ride="carousel">
				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <div class="item active">
				    	<div class="featuredImage col-lg-4 col-md-4 col-sm-4 col-xs-4">
					<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-dp.jpg">
				</div>
				<div class="featuredTitle col-lg-8 col-md-8 col-sm-8 col-xs-8">
					<h1>FEATURED MEMBER</h1>
					<h2>Mayumi Hayakawa-Marcelo</h2>
					<h3>Title : Intercontinental Manila</h3>
				</div>
				<div class="shortDesc pTm col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<p>Antonio&rsquo;s made it to the list of 
					Asia&rsquo;s 50 Best Restauant 2015.
					<br><br>
					The famed Tagaytay restaurant 
					featuing elegant and delectable 
					served in a polished and cozy 
					setting ranks forty eight on the list. 
					The only restaurant in the country
					that made it to the prestigious 
					awards.</p>
				</div>
				    </div>
				    <div class="item">
					    <div class="featuredImage col-lg-4 col-md-4 col-sm-4 col-xs-4">
					<img class="img-responsive" src="/Project/1_Website/Design/Main_Layout/images/other/sample-dp.jpg">
				</div>
				<div class="featuredTitle col-lg-8 col-md-8 col-sm-8 col-xs-8">
					<h1>FEATURED MEMBER</h1>
					<h2>Mayumi Hayakawa-Marcelo</h2>
					<h3>Title : Intercontinental Manila</h3>
				</div>
				<div class="shortDesc pTm col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<p>Antonio&rsquo;s made it to the list of 
					Asia&rsquo;s 50 Best Restauant 2015.
					<br><br>
					The famed Tagaytay restaurant 
					featuing elegant and delectable 
					served in a polished and cozy 
					setting ranks forty eight on the list. 
					The only restaurant in the country
					that made it to the prestigious 
					awards.</p>
				</div>
				    </div>
				  </div>
				</div>
				<div class="plugins pTm col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
						<h4>Date</h4>
						<iframe src="http://free.timeanddate.com/clock/i4pzoma2/n145/fn17/fs10/fcfff/tct/pct/ahl/tt1/tw0/tm3/td2" frameborder="0" width="100%" height="24" allowTransparency="true"></iframe>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
						<h4>Time</h4>
						<iframe class="pTxs" src="http://free.timeanddate.com/clock/i4pzopy4/n145/fn17/fs10/fcfff/tct/pct/ahl/th2/ts1" frameborder="0" width="100%" height="17" allowTransparency="true"></iframe>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
						<h4>Temperature</h4>
						<div id="weather"></div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
						<h4>Currency</h4>
						<h5 style="padding-top: 4px;">PHP</h5>
					</div>
				</div>
			</div>
		</section>
</div>
<div class="secondRow whiteBG">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12">MEMBER HOTELS</h1>
				<hr class="col-lg-3 col-md-3 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class="row pTxxl">
				<div class="slider1">
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
					   <div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
					   <div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-4.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center">
					   	<a href="#" id="viewHotel pTl"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-4.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <div class="ellipsis">
					   		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   </div>
						<div class="text-center pTl">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				</div>
		</div>
	</section>
</div>
<div class="thirdRow">
	<section class="container pBxxl pTxxl">
		<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 concierge pBm">
			<div class="row">
				<hr class="col-lg-3 col-md-3 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12 cityGuide">CITY GUIDE</h1>
				<hr class="col-lg-3 col-md-3 paddingLeft hidden-sm hidden-xs darkBlueBG">
			</div>
			<div class="row guideContainer pTxxl">
				<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
					<a href="#">
						<div class="circularImage img-responsive" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg');"></div>
						<h1 class="text-center pTxl">EAT</h1>
						<p class="text-center">Lorem ipsum dolor sit amet,  
							consectetuer adipiscing elit, 
							  sed diam nonummy nibh .</p>
					</a>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
					<a href="#">
						<div class="circularImage img-responsive" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg');"></div>
						<h1 class="text-center pTxl">PLAY</h1>
						<p class="text-center">Lorem ipsum dolor sit amet,  
							consectetuer adipiscing elit, 
							  sed diam nonummy nibh .</p>
					</a>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
					<a href="#">
						<div class="circularImage img-responsive" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg');"></div>
						<h1 class="text-center pTxl">STAY</h1>
						<p class="text-center">Lorem ipsum dolor sit amet,  
							consectetuer adipiscing elit, 
							  sed diam nonummy nibh .</p>
					</a>
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 concierge pBm pLxxl">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<h1 class="text-center col-lg-12 col-md-12 col-sm-12 col-xs-12 pBl">LIVE SOCIAL MEDIA FEED</h1>
					<div role="tabpanel">

					  <!-- Nav tabs -->
					  <ul class="nav nav-tabs" role="tablist">
					    <li role="presentation" class="active"><a href="#facebook" aria-controls="home" role="tab" data-toggle="tab" id="facebookIcon"></a></li>
					    <li role="presentation"><a href="#instagram" aria-controls="instagram" role="tab" data-toggle="tab" id="instagramIcon"></a></li>
					    <li role="presentation"><a href="#twitter" aria-controls="twitter" role="tab" data-toggle="tab" id="twitterIcon"></a></li>
					  </ul>
					
					  <!-- Tab panes -->
					  <div class="tab-content">
					    <div role="tabpanel" class="tab-pane active" id="facebook">Facebook News Feed Live</div>
					    <div role="tabpanel" class="tab-pane " id="instagram">Instagram News Feed Live</div>
					    <div role="tabpanel" class="tab-pane " id="twitter">Twitter News Feed Live</div>
					  </div>
					
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
