<div class="jumbotron" style="background-image:url('/Data/Images/<?php echo $this->_XMLObj->image[0]->path?>')">
</div>

<div class="aboutContainer whiteBG">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12"><?php echo $this->displayElement("title")?></h1>
				<hr class="col-lg-3 col-md-3 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class="col-lg-10 col-lg-offset-1 pTxxl">
				<?php echo $this->displayElement("page_content_editor")?>
		</div>
	</section>
</div>