<?php
$array_of_no_categories = array(
	"team",
	"pacific"
);

$page_id = routes::getInstance()->getCurrentTopLevelPageID();
$link_text = routes::getInstance()->getCurrentTopLevelLinkText();

?>
<?php //======================= DELETE ARTICLE ===================================================?>
<div id="deleteArticlePopup" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="deleteArticle" class="modal-content popup clearfix">
    	<div class="modal-body">
			<form method="POST" action="/<?php echo routes::getInstance()->getCurrentTopLevelURLName()?>/content/delete">
				<?php if($page_id == 'team') : ?>
					<h3>Delete Member</h3>
				<?php elseif($page_id == 'credentials') : ?>
					<h3>Delete Credentials</h3>
				<?php elseif($page_id == 'news') : ?>
					<h3>Delete News</h3>
					<?php elseif($page_id == 'recipes') : ?>
					<h3>Delete Recipes</h3>
				<?php else : ?>
					<h3>Delete Article</h3>
				<?php endif; ?>
				<div class="mVm">
					<?php if($page_id == 'team') : ?>
						<span>Are you sure you want to delete this member</span>
					<?php elseif($page_id == 'credentials') : ?>
						<span>Are you sure you want to delete this credential</span>
					<?php elseif($page_id == 'pacific') : ?>
						<span>Are you sure you want to delete this product</span>
					<?php elseif($page_id == 'news') : ?>
						<span>Are you sure you want to delete this news</span>
					<?php elseif($page_id == 'recipes') : ?>
						<span>Are you sure you want to delete this recipe</span>
					<?php else : ?>
						<span>Are you sure you want to delete this article</span>
					<?php endif; ?>
				</div>
				<input type="hidden" name="article_id" value="" />
				<input type="hidden" name="route_id" value="" />
				<div class="mTl clearfix align_c">
					<input type="submit" class="btn" value="Yes" />
					<span class="btn pointer mLm" data-dismiss="modal" title="cancel">CANCEL</span>
				</div>
			</form>
    	</div>
    </div>
  </div>
</div>

<?php //======================= ADD ARTICLE ===================================================?>
<div id="addArticlePopup" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="addArticle" class="modal-content popup clearfix">
    	<div class="modal-body">
			<form method="POST" id="addArticleForm" action="/<?php echo routes::getInstance()->getCurrentTopLevelURLName()?>/content/add">
				<?php if($page_id == 'team') : ?>
					<h3>Add Member</h3>
				<?php elseif($page_id == 'credentials') : ?>
					<h3>Add Credential</h3>
					<h3>Add Member</h3>
				<?php elseif($page_id == 'pacific') : ?>
					<h3>Add Product</h3>
				<?php elseif($page_id == 'news') : ?>
					<h3>Add News</h3>
				<?php elseif($page_id == 'recipes') : ?>
					<h3>Add Recipes</h3>
				<?php else : ?>
					<h3>Add Article</h3>
				<?php endif; ?>
				<span id="addError"></span>
					<div class="mVs">
						<?php if($page_id == 'team') : ?>
							<span>Member Name</span>
						<?php elseif($page_id == 'credentials') : ?>
							<span>Credential Title</span>
						<?php elseif($page_id == 'pacific') : ?>
							<span>Product Name</span>
						<?php elseif($page_id == 'news') : ?>
							<span>News Title</span>
						<?php elseif($page_id == 'recipes') : ?>
							<span>Recipe Name</span>
						<?php else : ?>
							<span>Article Title</span>
						<?php endif; ?>
						<input type="text" name="article_title"/>	
					</div>
					<div class="mTl clearfix align_c">
						<span class="btn" id="addArticleBtn">Add</span>
						<span class="btn pointer  mLm" title="cancel" data-dismiss="modal">CANCEL</span>
					</div>
			</form>
    	</div>
    </div>
  </div>
</div>

<?php //======================= DELETE CATEGORY ===================================================?>
<div id="deleteCategoryPopUp" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="deleteCategory" class="modal-content popup clearfix">
    	<div class="modal-body">
			<span class="deleteText fc_starfish_gray8 fwB">Are you sure you want to <span class="fc_starfish_red">DELETE</span> this Category?</span>
			<div id="buttonContainer" class="align_c clearfix">
				<form method="POST" action="/<?php echo routes::getInstance()->getCurrentTopLevelURLName()?>/category/delete">
					<input name="article_category_id" type="hidden" value="">
					<input class="btn yes delete_subcategory_confirm pointer mTs" title="Delete this category" type="submit" name="delete_category" value="Yes">
					<span class="btn pointer closeDialog mLm mTs" data-dismiss="modal" title="cancel">CANCEL</span>
				</form>
			</div>
    	</div>
    </div>
  </div>
</div>


<?php //======================= ADD CATEGORY ===================================================?>
<div id="addCategoryPopup" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="addCategory" class="modal-content popup clearfix">
    	<div class="modal-body">
			<form method="POST" id="addCategoryForm" action="/<?php echo routes::getInstance()->getCurrentTopLevelURLName()?>/category/add">
				<h3>Add Category</h3>
				<span id="addError"></span>
					<div class="mVs">
						<span>Category Name</span>	
						<input type="text" name="category_name"/>	
					</div>
					<div class="mTl clearfix align_c">
						<span class="btn" id="addCategoryBtn">Add</span>
						<span class="btn pointer mLm" data-dismiss="modal" title="cancel">CANCEL</span>
					</div>
			</form>
    	</div>
    </div>
  </div>
</div>


<?php //======================= DELETE COMMENT ===================================================?>
<div id="deleteCommentPopup" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div id="deleteArticle" class="modal-content popup clearfix">
			<div class="modal-body">
				<form method="POST" action="/<?php echo routes::getInstance()->getCurrentTopLevelURLName()?>/comment/delete">
					<h3>Delete Comment</h3>
					<div class="mVm">
						<span>Are you sure you want to delete this comment</span>
					</div>
					<input type="hidden" name="article_comment_id" value="" />
					<div class="mTl clearfix align_c">
						<input type="submit" class="btn" value="Yes" />
						<span class="btn pointer mLm" data-dismiss="modal" title="cancel">CANCEL</span>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>