<div class="pressContainer whiteBG">
	<section class="container pBxl pTxxl featuresContainer">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">FEATURES</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class=" pTxxl">
			<?php echo $this->displayElement("features_editor")?>
		</div>
	</section>
</div>