<div class="hotelsContainer blackGradient">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">PRESS ROOM</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class=" pTxxl">
			<div class="slider1">
			<?php foreach($this->press_room as $press):?>
			  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
			  	<img src="<?php echo $press["image_path"]?>">
			  	<div class="card_content">
				   <h2><?php echo $press["article_title"]?></h2>
				   <p><?php echo $press["content"]?></p>
				   <div class="text-center">
				   </div>
				</div>
			  </div>
				   	<a href="/press-room/view/<?php echo $press["permalink"]?>" id="viewHotel"></a>
			  <?php endforeach?>
			</div>
		</div>
	</section>
</div>