<div class="pressContainer whiteBG">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">PRESS ROOM</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pTxxl pressListings">
			<?php foreach($this->press_room as $press):?>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 perListing pTxxl">
			  		<div class="imgContainer col-lg-5 col-md-5 col-sm-12 col-xs-12">
				     	<img class="img-responsive" src="<?php echo $press["image_path"]?>">
					</div>
					<div class="ellipsis descContainer col-lg-7 col-md-7 col-sm-12 col-xs-12">
						<h2><?php echo $press["article_title"]?></h2>
						<hr class="darkBlueBG">
						<p><?php echo $press["content"]?></p>
			  		</div>
			  		<a href="/press-room/view/<?php echo $press["permalink"]?>">Read more &raquo;</a>
			 	</div>
			<?php endforeach?>
		</div>
	</section>
</div>