<div class="pressContainer whiteBG">	
	<div class="container pressInner">
		<div class="row pTxxl">
			<a href="/press-room">Back &raquo;</a>
			<h1 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $this->pres["article_title"]?></h1>
			<p class="pLm"><?php echo date("F m, Y", $this->pres["date_created"])?></p>
			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">	
				<img class="img-responsive" src="<?php echo $this->pres["image_path"]?>">
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<p><?php echo $this->pres["content"]?></p>
			</div>
		</div>
	</div>
</div>