<div class="hotelsContainer blackGradient">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12"><?php echo $this->pres["article_title"]?></h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
	</section>
	
	<div class="container ">
		<div class="row pTxxl">
			<p><?php echo date("F m, Y", $this->pres["date_created"])?></p>
			<img src="<?php echo $this->pres["image_path"]?>">
			<p><?php echo $this->pres["content"]?></p>
		</div>
	</div>
</div>