<div id="container" class="fleetManned">
  <div id="left">
  </div>

  <header style=" background:url('<?php echo "/Data/Images/".$this->_XMLObj->image[0]->path?>') no-repeat">
    <div class="overlay"></div>
  </header>

  <div id="middle">
     <div class="header">
        <p><?php echo $this->displayElement("page_banner_title")?></p>
     </div>
        
   	 <div class="breadcrumb">
     	<span class="breadcrumb-0 first">
        	<a href="/">Home</a>
        </span>
        <span class="breadcrumb-1">
        	 <a href="/company.html" class="active">Company</a>
        </span>
        <span class="active">Fleet Manned</span>
     </div>    
     <section id="content">
        <h1 class="page-title"><?php echo $this->displayElement("page_title")?></h1>      
        <div class="region region-content">
    		<div class="container-fluid">
                        <?php echo $this->displayElement("page_content_editor")?>
            </div>                         
  		</div>
    	</section>
        <aside id="right">
            %%SIDE_NAV%%
    	</aside>
  	</div>
</div>


