<div class="region region-right">
        		<div id="block-menu-block-1" class="block block-menu-block">
  					<div class="content">
    					<div class="menu-block-wrapper menu-block-1 menu-name-main-menu parent-mlid-0 menu-level-2">
  								<?php 
  									$url = $this->getValueOfURLParameterPair("company");
  								?>
  							<ul class="menu">
                            	<li class="<?php echo $url == NULL ? "active" : ""?> first leaf menu-mlid-687">
                                	<a href="/company">Welcome to our website</a>
                                </li>
								<li class="<?php echo $url == "company-profile" ? "active" : ""?> leaf menu-mlid-547">
                                	<a href="/company/company-profile">Company Profile</a>
                                </li>
								<li class="<?php echo $url == "our-services" ? "active" : ""?>  leaf menu-mlid-457">
                                	<a href="/company/our-services">Our Services</a>
                                </li>
                                <li class="<?php echo $url == "fleet-manned" ? "active" : ""?>  leaf menu-mlid-526">
                                	<a href="/company/fleet-manned">Fleet Manned</a>
                                </li>
                                <li class="<?php echo $url == "csr" ? "active" : ""?>  leaf menu-mlid-526">
                                	<a href="/csr">CSR</a>
                                </li>
                                <li class="<?php echo $url == "accreditations" ? "active" : ""?>  leaf menu-mlid-527">
                                	<a href="/company/accreditations">Accreditations</a>
                                </li>
                                <li class="<?php echo $url == "quality-policy" ? "active" : ""?>  leaf menu-mlid-462">
                                	<a href="/company/quality-policy">Quality Policy</a>
                                </li>
                                <li class="<?php echo $url == "avior-standards" ? "active" : ""?>  leaf menu-mlid-528">
                                	<a href="/company/avior-standards">Avior Standards</a>
                                </li>
                                <li class="<?php echo $url == "links-downloads" ? "active" : ""?>  leaf menu-mlid-494">
                                	<a href="/company/links-downloads">Links and Downloads</a>
                                </li>
                            </ul>
                        </div>
  					</div>
				</div>
  			</div>
