<div class="membersContainer whiteBG">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-3 col-md-3 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-5 col-md-5 col-sm-12 col-xs-12 clefsdorBlue">ADHERENT MEMBERS</h1>
				<hr class="col-lg-3 col-md-3 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class=" pTxxl">
			<div class="slider1">
			<?php foreach($this->members as $member):?>
			  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
			  	<img src="<?php echo $member["image_path"]?>">
			  	<div class="card_content">
				   <h2><?php echo $member["article_title"]?></h2>
				   <div class="ellipsis">
				   		<p><?php echo $member["content"]?></p>
				   </div>
				   <div class="text-center pTl">
				   	<a href="/members/view/<?php echo $member["permalink"]?>" id="seeMore"></a>
				   </div>
				</div>
			  </div>
			  <?php endforeach?>
			</div>
		</div>
	</section>
</div>