<div class="membersContainer darkBlueBG">

	<div class="container profileContainer">
		<div class="row pTxxl pBxxl">
			<div class="imgContainer col-lg-4 col-md-4 col-lg-offset-1 col-md-offset-1 col-sm-12 col-xs-12">
			     <img class="img-responsive" src="<?php echo $this->member["image_path"]?>">
			</div>
			<div class="descContainer col-lg-6 col-md-6 col-sm-12 col-xs-12">
				<h1><?php echo $this->member["article_title"]?></h1>
				<h2>Title:<?php echo $this->member["position"]?></h2>
				<hr>
				<p><?php echo $this->member["content"]?></p>
			</div>
			<div class="col-lg-1 col-md-1 col-sm-12 col-xs-12""></div>
		</div>
	</div>
	
	<div class="whiteBG">
		<div class="container ">
			<div class="row pTxxl">
				<div class="imgContainer col-lg-5 col-md-5 col-sm-12 col-xs-12">
				     <img class="img-responsive" src="<?php echo $this->member["hotel_image"]?>">
				</div>
				<div class="descContainer col-lg-7 col-md-7 col-sm-12 col-xs-12">
					<h1><?php echo $this->member["hotel_name"]?></h1>
					<hr>
					<p><?php echo $this->member["hotel_description"]?></p>
					<div class="">
					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>