<div class="membersContainer whiteBG">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">MEMBERSHIP</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
	</section>
	<div class="container">
		<div class="row">
			<img src="/Data/Images/<?php echo $this->_XMLObj->image[0]->path?>">
			<p><?php echo $this->displayElement("page_content_editor")?></p>
		</div>
	</div>
</div>