<!-- <div class="jumbotron" style="background-image:url('/Project/1_Website/Design/Main_Layout/images/backgrounds/about-us-banner.jpg')">
</div> -->

<div class="contactContainer blackGradient">
	<section class="container pBxxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">CONTACT US</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class="row">
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-2 pTxxl">
				<h2 class="text-center col-xs-12">Lorem Ipsum dolor sit amet, consectetuer adipiscing elit,  sed diam nonummy nibh</h2>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pTxxl">
					<form action="/contact/sendEmail" method="POST" data-toggle="validator" role="form">
		            	<div class="form-group">
		            		<label for="name">NAME:</label>
						    <input id="name" type="text" name="name" class="form-control" required>
		                </div>
		                <div class="form-group">
		                	<label for="contact-number">CONTACT NUMBER:</label>
		                    <input type="tel" name="telephone" class="form-control" id="contact-number" required>
		                </div>
		                <div class="form-group">
		                	<label for="email">EMAIL ADDRESS:</label>
		                    <input type="email" name="email" class="form-control" id="email" required>
		                </div>
		                <div class="form-group">
		                	<label for="company">COMPANY:</label>
		                    <input type="text" name="company" class="form-control" id="company" required>
		                </div>
		                <div class="form-group">
		                	<label for="message">MESSAGE</label>
		                    <textarea class="form-control" rows="8" name="message" id="message"></textarea>
		                </div>
		                <button type="submit" class="fright" id="submitBtn"></button>
		             </form>
		        </div>
		        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1 pTxxl">
					<h3 class="col-xs-12">LES CLEF D'OR CONTACT INFORMATION</h2>
		        </div>
			</div>
		</div>
	</section>
</div>
