<div id="container">
  		<div id="left"></div>

  	<header style=" background:url('<?php echo "/Data/Images/".$this->_XMLObj->image[0]->path?>') no-repeat">
    	<div class="overlay"></div>
  	</header>

  	<div id="middle">
		<div class="header">
			<p><?php echo $this->displayElement("page_banner_title")?></p>
      	</div>
        
    	<div class="breadcrumb">
        	<span class="breadcrumb-0 first">
            	<a href="/">Home</a>
            </span>
            <span class="active">Contact Us</span>
         </div>    
         <section id="content">
            <h1 class="page-title"><?php echo $this->displayElement("page_title")?></h1>
        		<div class="region region-content">
                    <div class="container-fluid">
                        <div class="block block-views col-xs-3 col-md-3">
                                <div class="content">
                                    <div class="view view-display-id-block">
                                        <div class="view-content">
                                            <div class="views-row views-row-1 views-row-odd views-row-first views-row-last">
                                                <div class="views-field contactDetails">        
                                                        <?php echo $this->displayElement("page_content_editor")?>  
                                                </div>
                                                <div class="views-field applyButton">        
                                                    <h2 class="field-content block-contact-apply">  
                                                         <a href="/careers">APPLY ONLINE</a>
                                                    </h2>  
                                                </div>  
                                              </div>
                                           </div> 
                                        </div>
                                    </div>
                                </div>
							<div class="block block-views col-xs-6 col-md-6 col-lg-6 col-xs-offset-2">
                                <div class="content">
                                    <div class="view view-display-id-block view-dom-id-df30aaa6313325594ef54decfbdd5ea5">
                                        <div class="view-content">
                                            <div class="views-row views-row-1 views-row-odd views-row-first views-row-last">
                                                <div class="views-field">        
                                                    <div class="field-content inquiry">
                                                        <h1>GET IN TOUCH WITH US</h1>
                                                        <p>For inquiries, please fill up the form below</p>
                                                     </div>  
                                                </div>  
                                                <div class="views-field">        
                                                    <div class="field-content">
                                                        <form action="/contact/sendEmail" method="POST" data-toggle="validator" role="form">
                                                          <div class="form-group">
                                                            <input type="text" name="name" class="form-control" placeholder="Name*" required>
                                                          </div>
                                                          <div class="form-group">
                                                            <input type="text" name="comapny" class="form-control" placeholder="Company / Occupation">
                                                          </div>
                                                          <div class="form-group">
                                                            <input type="tel" name="telephone" class="form-control" placeholder="Telephone*" required>
                                                          </div>
                                                          <div class="form-group">
                                                            <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email*" required>
                                                          </div>
                                                          <div class="form-group">
                                                            <select class="form-control">
                                                              <option>1</option>
                                                              <option>2</option>
                                                              <option>3</option>
                                                              <option>4</option>
                                                              <option>5</option>
                                                            </select>
                                                          </div>
                                                          <div class="form-group">
                                                            <textarea class="form-control" rows="8" name="message"></textarea>
                                                          </div>
                                                          <button type="submit" class="btn btn-default fright">Submit</button>
                                                        </form>
                                                    </div>  
                                                </div>  
                                              </div>
                                           </div> 
                                        </div>
                                    </div>
                                </div>
							</div>
						</div> 
				</section>
			</div> 
		</div>

		

<div class="modal fade" id="thankyou" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  	<div class="modal-content">
  		<div class="modal-header">
			<input type="hidden" name="success" value="<?php echo isset($_GET["success"]) ? "1" : "0" ?>">
			<h4 class="topPointer show modal-title fleft" id="myModalLabel"></h4>
		    <div class="closeButton fright">
				<button type="button" class="close pointer" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		</div>
	    <div class="applyContent modal-body">
			<h3 class="ffhoeflerRoman ">Thank you!</h3>
			<p>Your application has been received. We will get back to you shortly.</p>
	    </div>
	    <div class="modal-footer">
        </div>
	</div>
  </div>
</div>	