<footer class="footer blackGradient">
      <div class="container">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-left mTm">
        	<h1 class="mRs connect">CONNECT :</h1>
        	<a href="#" id="facebookConnect"></a>
        	<a href="#" id="twitterConnect"></a>
        	<a href="#" id="instagramConnect"></a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-right">
            <!-- Collect the nav links, forms, and other content for toggling -->
	         <h1 class="text-right mTm">&copy;ALL RIGHTS RESERVED 2015</h1>
	    </div>
            <!-- /.navbar-collapse --
        </div><!-- /.container -->     
        </div>
      <div class="container">
        <div class="text-center">
        	<img class="img-responsive mAuto" src="/Project/1_Website/Design/Main_Layout/images/other/clefs-footer-logo.png">
        </div>
      </div>
</footer>