<link rel="stylesheet" href="/Project/2_Enterprise/Design/Plugins/tagInput/jquery.tagsinput.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/Project/2_Enterprise/Design/Applications/Job_Manager/Main_App_Layout/css/jobs.css" type="text/css" media="screen" />

<script type="text/javascript" src="/Project/2_Enterprise/Design/Plugins/tagInput/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/Project/2_Enterprise/Design/Applications/Job_Manager/Main_App_Layout/templates/inpage_javascript.js"></script>
