<!-- outer wrapper start-->
<div id="outer_wrapper" class="clearfix posRel">
<div id="photo_chooser"></div>


<div>
	<!-- left hand nav -->
	<div class="col-xs-3"> 
	%%APPLICATION_LEFT_COLUMN%%
	<!-- left hand nav end -->
	</div> 
	
	<!-- content column start -->
	<div id="contentColumn" class="col-xs-9">
		<div id="applicationContent">
			%%APPLICATION_CONTENT%%
		</div>
	<!-- content column end -->
	</div>
</div>
	
</div>
<!-- outer wrapper end-->
%%POPUP_DIALOG%%
<div class="transparent_background hide"></div>
