


<?php $jobs = $this->jobs?>
<?php if($jobs):?>
<?php foreach($jobs as $job):?>
<div class="views-field career">        
	<div class="field-content">
		<div class="row careerContainer">
			<div class="careersWrapper careersList careerBox">
				<h1 class="topPointer show careerTitle"><?php echo $job->job_title?></h1>
				<a href="#" data-toggle="modal" data-target="#readMoreDialog_<?php echo $job->job_id?>">READ MORE</a>
			</div>
		</div>
	</div>
</div>
<?php endforeach?>
<?php endif?>


<?php if($jobs):?>
<?php foreach($jobs as $job):?>
<div class="modal fade" id="readMoreDialog_<?php echo $job->job_id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  	<div class="modal-content">
  		<div class="modal-header">
			<h4 class="topPointer show modal-title fleft" id="myModalLabel"><?php echo $job->job_title?></h4>
		    <div class="closeButton fright">
				<button type="button" class="close pointer" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		</div>
	    <div class="applyContent modal-body"><?php echo $job->job_description;?></div>
	    <div class="modal-footer">
	    	<a href="/careers/online-form/apply/<?php echo $job->job_permalink?>" class="applyButton btn btn-primary">APPLY</a>	
        </div>
	</div>
  </div>
</div>
<?php endforeach?>
<?php endif?>


