<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper" class="clearfix">

<div id="middle">
	
	<header style=" background:url('<?php echo "/Data/Images/".$this->_XMLObj->image[0]->path?>') no-repeat">
		<div class="overlay"></div>
	</header>

  	<div class="header">
  		<p>Our Philosophy Your Crew, Our Care.</p>
  	</div>
        
	<div class="breadcrumb">
		<span class="breadcrumb-0 first">
        	<a href="/">Home</a>
        </span>
        <span class="breadcrumb-1">
        	 <a href="/careers" class="active">Careers</a>
        </span>
	</div>   

<section id="content">
	<h1 class="page-title"></h1>
	<div class="region region-content">
		<div class="container-fluid">
			<div class="block block-views col-xs-12 col-md-12">
				<div class="content">
					<div class="view view-display-id-block view-dom-id-df30aaa6313325594ef54decfbdd5ea5">
						<div class="view-content">
							<div class="views-row views-row-1 views-row-odd views-row-first views-row-last">
								<div class="views-field">
									<div class="field-content">
                                         <h1>GET IN TOUCH WITH US</h1>
                                         <p class="pLm">For inquiries, please fill up the form below</p>
                                    </div>
                                </div>
                                <div class="views-field">
									<div class="field-content">
                                         <h2>Create Application</h2>
                                         <p class="pLm">Note: Cells with () must be filled in. Type "N/A" if information is not applicable to you.</p>
                                    </div>
                                </div>
								<div class="fleft clearfix formWrap">
									<form id="createApplicationForm" method="post" enctype="multipart/form-data" action="/careers/online-form/sendCreatedApplication" class="clearfix posRel application_form">
									<input type="hidden" value='<?php echo $this->job["job_id"]?>' name="job_id" />
										<div class="views-field borderContainer">
											<div class="field-content">
												<div class="formHead clearfix">
													<h2 class="pTitle">Personal Information</h2>
												</div>
												<div class="formContainer">
													<p id="errorMsg" class="red w">Please check if you completed the  fields before proceeding</p>
													<div class="clearfix">
														<div id="photoField" class="clearfix">
															<div class="clearfix attachPhoto posRel from-group">
																<input type="text" id="fileVal" class="fleft form-control" readonly>
																<div id="dummyPhoto" class="fleft photoAttach pointer">
																	<input type="file" id="photo" name="photo">
																	<div id="thumb"></div>
																</div>
																<p class="fleft" id="error_photo" style="color:red"></p>
																<p class="fleft mLm mTs">(Optional)</p>
															</div>
														</div>
													</div>
													<div id="nameField" class="clearfix mVs posRel mTl form-group">
															<input type="text" name="first_name" class="w269 mRs form-control" placeholder="First name" value="" />
															<input type="text" name="middle_name" class="w269 mRs form-control" placeholder="Middle name" value="" />
															<input type="text" name="last_name" class="w269 form-control" placeholder="Last name"  value=""/>
													</div>
													<div id="birthField" class="w300 clearfix mVs fleft form-group">
														<p class="fleft mRl"><span>Date of Birth</span></p>
														<?php dropdown_renderer::$year_start = 1950?>
														<?php $class = array("months" => "w55 mRs ", "days" => "w50 mRs ", "years" => "w60 ")?>
														<?php echo dropdown_renderer::makeDatePicker("date_of_birth", $class);?>
													</div>
													<div id="availableField" class="w300 clearfix mVs fleft form-group">
														<?php dropdown_renderer::$year_start = 2014?>
														<?php dropdown_renderer::$year_end   = 2040?>
														<p class="fleft mRl"><span>Available From</span></p>
														<?php $class = array("months" => "w55 mRs displayInline", "days" => "w50 mRs displayInline", "years" => "w60 displayInline")?>
														<?php echo dropdown_renderer::makeDatePicker("available_date", $class);?>
													</div>
													<div id="addressField" class="clearfix mVs form-group">
														<input type="text" name="address" class="w595 form-control" placeholder="Address" value=""/>
													</div>
													<div id="numberField" class="clearfix mVs form-group">
														<input type="text" name="mobile_number" class="w290 fleft mRs form-control w412" placeholder="Mobile phone" value=""/>
														<input type="text" name="landline_number" class="w290 mRs form-control w412" placeholder="Landline phone" value=""/>
													</div>
													<div class="clearfix mVs form-group">
														<input type="text" name="email" class="w290 fleft mRs required form-control w412" placeholder="Email Address*" value=""/>
														<input type="text" name="confirm_email" class="w290 required form-control w412" placeholder="Confirm Email Address*" value=""/>
													</div>
													<div class="clearfix mVs form-group">
														<input type="text" name="rank_applied" class="w290 fleft mRs form-control w412" placeholder="Rank Applied for" value=""/>
														<?php echo dropdown_renderer::makeCitizenshipPicker("nationality", "", "Filipino", "w290");?>
													</div>
													<div class="clearfix mVs form-group">
														<input type="text" name="preferred_ship_type" class="w190 fleft mRs form-control w412" placeholder="Preferred Ship Type" value=""/>
														<input type="text" name="salary_expectation" class="w190 fleft form-control w412" placeholder="Salary Expectations (USD)" value=""/>
													</div>
												</div>
											</div>
										</div>
										<div class="views-field borderContainer mTl">
											<div class="field-content">
												<div class="formHead clearfix">
													<h2 class="pTitle">Documents / Certification / Visa</h2>
												</div>
												<div class="formContainer">
													<p id="errorMsg" class="red hide">Please check if you completed the  fields before proceeding</p>
													<div class="clearfix mVs">
														<div id="passField" class="clearfix fleft w300 mRs form-group">
															<input type="text" name="passport_number" class="w300 form-control w412" placeholder="Passport Number" value="" />
														</div>
														<div id="passValidField" class="clearfix fleft form-group w412">
															<p class="fleft mRs"><span>Valid Until</span></p>
															<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
															<?php echo dropdown_renderer::makeDatePicker("passport_validity", $class);?>
														</div>
													</div>
													<div class="clearfix mVs">
														<div id="seabookField" class="clearfix fleft w300 mRs form-group">
											 				<input type="text" name="seamans_number" class="w300 form-control w412" placeholder="Seamanbook Number" value="" />
														</div>
														<div id="seaValidField" class="clearfix fleft form-group w412">
															<p class="fleft mRs"><span>Valid Until</span></p>
															<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
															<?php echo dropdown_renderer::makeDatePicker("seamans_validity", $class);?>
														</div>
													</div>
													<div class="clearfix mVs">
														<div id="cocField" class="clearfix fleft w300 mRs form-group">
															<input type="text" name="coc_number" class="w200 mRs form-control displayInline" placeholder="COC" value="" />
															<select name="coc_level" class="w200 form-control displayInline">
																<option value="" selected disabled>COC Level</option>
																<option value="Management">Management</option>
																<option value="Operational">Operational</option>
																<option value="Support">Support</option>
																<option value="Cook">Cook</option>
															</select>
														</div>
														<div id="cocValidField" class="clearfix w280 fleft form-group w412">
															<p class="fleft mRs"><span>Valid Until</span></p>
															<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
															<?php echo dropdown_renderer::makeDatePicker("coc_validity", $class);?>
														</div>
													</div>
													<div class="clearfix mVs">
														<div class="clearfix fleft w300 mRs form-group w412">
															<input type="text" name="us_visa" class="w300 form-control" placeholder="US Visa" value="" />
														</div>
														<div id="visaValidField" class="clearfix fleft form-group w412">
															<p class="fleft mRs"><span>Valid Until</span></p>
															<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
															<?php echo dropdown_renderer::makeDatePicker("us_visa_validity", $class);?>
														</div>
													</div>
													<div class="clearfix mVs form-group">
														<textarea name="additional_skills" class="form-control" rows="4" placeholder="Additional skills / certifications / land based experience  (please mention if you think they are relevant to your application)"></textarea>
													</div>
												</div>
											</div>
										</div>
										<div class="views-field borderContainer mTl">
											<div class="field-content">
												<div class="formHead clearfix">
													<h2 class="pTitle">SEASERVICE (will be checked against SMB) Please start with most recent contract first.</h2>
												</div>
												<div class="formContainer">
													<?php dropdown_renderer::$year_start = 1970?>
													<?php dropdown_renderer::$year_end   = 2040?>
													<?php foreach(range(1 ,20) as $i):?>
													<div data-ctr="<?php echo $i?>" class="serviceContainer clearfix <?php echo ($i == 1) ? "" : "hide"?>">
															<div class="clearfix">
																<div class="clearfix mVs form-group">
																	<input type="text" name="service[<?php echo $i?>][ship_name]" class="w269 mRs form-control displayInline" placeholder="Ship Name" value="">
																	<input type="text" name="service[<?php echo $i?>][ship_type]" class="w269 mRs form-control displayInline" placeholder="Ship Type" value="">
																	<input type="text" name="service[<?php echo $i?>][grt]" class="w269 form-control displayInline" placeholder="GRT" value="">
																</div>
																<div class="clearfix mVs form-group">
																	<input type="text" name="service[<?php echo $i?>][rank]" class="w410 mRs form-control displayIb" placeholder="Rank" value="">
																	<input type="text" name="service[<?php echo $i?>][flag]" class="w410 form-control displayIb" placeholder="Flag" value="">
																</div>
																<div class="clearfix mVs form-group">
																	<input type="text" name="service[<?php echo $i?>][manning_agency]" class="w410 mRs form-control displayIb" placeholder="Manning Agency" value="">
																	<input type="text" name="service[<?php echo $i?>][principal]" class="w410 form-control displayIb" placeholder="Principal" value="">
																</div>
																<div class="clearfix mVs form-group">
																	<input type="text" name="service[<?php echo $i?>][engine_make]" class="w410 mRs form-control displayIb" placeholder="Engine Make (Engineers only)" value="">
																	<input type="text" name="service[<?php echo $i?>][engine_kw]" class="w410 form-control displayIb" placeholder="Engine KW (Engineers only)" value="">
																</div>
																<div class="clearfix mVs">
																	<div id="signOnField" class="clearfix w280 fleft mRs form-group w410">
																		<p class="fleft mRs"><span>Sign on date</span></p>
																		<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
																		<?php echo dropdown_renderer::makeCustomDatePicker("service[$i][from_date", $class);?>
																	</div>
																	<div id="signOffField" class="clearfix w280 fright form-group w410">
																		<p class="fleft mRs"><span>Sign off date</span></p>
																		<?php $class = array("months" => "mm w55 mRs form-control displayInline", "days" => "dd w50 mRs form-control displayInline", "years" => "yy w60 form-control displayInline")?>
																		<?php echo dropdown_renderer::makeCustomDatePicker("service[$i][to_date", $class);?>
																	</div>
																</div>
															<hr class="mVxl">
															</div>
														</div>
													<?php endforeach?>
													<div class="text-center"><?php echo recaptcha_get_html(PUBLIC_KEY);?></div>
												</div>
											</div>
										</div>
										
										<div class="clearfix mTl fright">
											<input id="submitApplication" class="ArvilSans button orangeButton pAs pointer mRm fright btn" type="submit" value="SUBMIT APPLICATION">
											<span id="add_service" class="ArvilSans button blue pAsbutton pAs pointer mRm fright btn">&plus;ADD ANOTHER SEASERVICE</span>
										</div>
										</form>
					
						
							<button class="hide" id="toggleSubmitConfirmation" data-toggle="modal" data-target="#processApplication">Submit</button>
													</div>
								</div>							
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
</div>