<div class="views-field">       
	<div class="field-content quickApplyBox">
		<p class="optionPar">This option is for senior officers only.</p>
		<form method="post" id="quick_apply_from" action="/careers/online-form">
		<?php if($this->has_error):?>
			<p class="error" style="color:red;">***Invalid Captcha***</p>
		<?php endif?>
		<div class="form-group">
			<input type="text" name="full_name" class="required form-control" value="<?php echo isset($_POST['full_name']) ? $_POST['full_name'] : ""?>" placeholder="Full Name*"/>
		</div>
		<div class="form-group">
			<select name="rank" class="required form-control">
				<?php if(isset($_POST["rank"])):?>
				<option selected value="<?php echo $_POST["rank"]?>" ><?php echo $_POST["rank"]?></option>
				<?php endif;?>
				<option value="">-Select Rank*-</option>
				<option value="Master" >Master</option>
				<option value="CHOFF" >CHOFF</option>
				<option value="CHENG" >CHENG</option>
				<option value="2ENG"  >2ENG</option>
			</select>
		</div>
		<div class="form-group">
			<?php dropdown_renderer::$year_start = 1950?>
			<?php $class = array("months" => "dd required", "days" => "mm required", "years" => "yy required")?>
			<?php echo dropdown_renderer::makeDatePicker("date_of_birth", $class);?>
		</div>
		<div class="form-group">
			<input type="text" name="phone" class="required form-control" value="<?php echo isset($_POST['phone']) ? $_POST['phone'] : ""?>" placeholder="Phone*"/>
		</div>
		<div class="form-group">
			<input type="text" name="email" class="required form-control" value="<?php echo isset($_POST['email']) ? $_POST['email'] : ""?>" placeholder="Email" />
		</div>	
		<div class="form-group">
			<select name="vessel_type" class="required form-control">
						<?php if(isset($_POST["vessel_type"])):?>
						<option selected value="<?php echo $_POST["vessel_type"]?>"><?php echo $_POST["vessel_type"]?></option>
						<?php endif;?>
						<option value="">-Select Vessel Type*-</option>
						<option value="Bulk">Bulk</option>
						<option value="Container">Container</option>
						<option value="Refeer">Reefer</option>					
						<option value="General Cargo">General Cargo</option>
						<option value="Tanker-Oil">Tanker-Oil</option>
						<option value="Tanker-Gas">Tanker-Gas</option>
						<option value="Tanker-Chemical">Tanker-Chemical</option>
						<option value="Passenger">Passenger</option>
						<option value="RoRo">RoRo</option>
						<option value="Heavy Lift">Heavy Lift</option>
						<option value="AHST">AHST</option>
						<option value="Harbour Tug">Harbour Tug</option>
						<option value="Supply Vessel">Supply Vessel</option>
						<option value="Crew Boat">Crew Boat</option>
						<option value="Others">Others</option>
				</select>
		</div>
		<div class="form-group">
			<textarea name="comment" placeholder="Comment" class="form-control" rows="4"><?php echo isset($_POST['comment']) ? $_POST['comment'] : ""?></textarea>
		</div>
		<div id="recaptchaContainer" class="clearfix hide">
			<div><?php echo recaptcha_get_html(PUBLIC_KEY);?></div>
			<span id="recaptcha_submit" style="background-color:rgb(16, 72, 116); color:white; font-size:15px" >Submit</span>
		</div>
		<input class="btn btn-default fright" type="submit" name="quick_apply" value="Submit"  />
	</form>
	</div>
	</div>
	

<div class="modal fade" id="thankyou" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
  	<div class="modal-content">
  		<div class="modal-header">
			<input type="hidden" name="success" value="<?php echo isset($_GET["success"]) ? "1" : "0" ?>">
			<h4 class="topPointer show modal-title fleft" id="myModalLabel"></h4>
		    <div class="closeButton fright">
				<button type="button" class="close pointer" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
		</div>
	    <div class="applyContent modal-body text-center mTl">
			<h3 class="ffhoeflerRoman ">Thank you!</h3>
			<p class="text-center">Your application has been received. We will get back to you shortly.</p>
	    </div>
	    <div class="modal-footer">
        </div>
	</div>
  </div>
</div>