<div class="hotelsContainer whiteBG">
	<section class="hotelInner">	
		<div class="container ">
				<div class="row pTxxl pBxxl">
					<div class="imgContainer col-lg-5 col-md-5 col-sm-12 col-xs-12">
					     <img class="img-responsive" src="<?php echo $this->hotel["image_path"]?>">
					</div>
					<div class="descContainer col-lg-7 col-md-7 col-sm-12 col-xs-12">
						<h1><?php echo $this->hotel["article_title"]?></h1>
						<hr>
						<p><?php echo $this->hotel["hotel_description"]?></p>
						<div class="">
						
						</div>
					</div>
				</div>
			</div>
	</section>
</div>