<div class="hotelsContainer blackGradient">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12"><?php echo $this->hotel["article_title"]?></h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
	</section>
	
	<div class="row pTxxl">
		<img src="<?php echo $this->hotel["image_path"]?>">
		<p><?php echo $this->hotel["hotel_description"]?></p>
	</div>
</div>