<div class="hotelsContainer whiteBG">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs darkBlueBG">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">HOTELS</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs darkBlueBG">
		</div>
		<div class=" pTxxl">
			<div class="slider1">
			<?php foreach($this->hotels as $hotel):?>
			  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
			  	<img src="<?php echo $hotel["image_path"]?>">
			  	<div class="card_content">
				   <h2><?php echo $hotel["article_title"]?></h2>
				   <div class="ellipsis">
				   		<p><?php echo $hotel["hotel_description"]?></p>
				   </div>
				   <div class="text-center pTl">
				   	<a href="/hotels/view/<?php echo $hotel["permalink"]?>" id="viewHotel"></a>
				   </div>
				</div>
			  </div>
			  <?php endforeach?>
			</div>
		</div>
	</section>
</div>