<div class="hotelsContainer blackGradient">
	<section class="container pBxl pTxxl">
		<div class="row">
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 hidden-sm hidden-xs">
				<h1 class="text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">HOTELS</h1>
				<hr class="col-lg-4 col-md-4 col-sm-4 col-xs-4 paddingLeft hidden-sm hidden-xs">
		</div>
		<div class=" pTxxl">
				<div class="slider1">
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
					   <div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-4.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-4.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-1.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-3.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  	</div>
				  <div class="slide col-lg-3 col-md-3 col-sm-3 col-xs-12">
				  	<img src="/Project/1_Website/Design/Main_Layout/images/other/slide-2.jpg">
				  	<div class="card_content">
					   <h2>LOREM IPSUM</h2>
					   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint natus itaque ex laborum praesentium soluta velit repudiandae deserunt magni ut dolorem obcaecati labore voluptatem reiciendis placeat tempora nisi ab laboriosam.</p>
						<div class="text-center">
					   	<a href="#" id="viewHotel"></a>
					   </div>
					</div>
				  </div>
				</div>
		</div>
	</section>
</div>