<div id="container">
  		<div id="left">
  		</div>

  		<header style=" background:url('<?php echo "/Data/Images/".$this->_XMLObj->image[0]->path?>') no-repeat">
    		<div class="overlay"></div>
  		</header>

  		<div id="middle">
			<div class="header">
				<p>Lorem Ipsum. Lorem Ipsum.</p>
      		</div>
    		<div class="breadcrumb">
            	<span class="breadcrumb-0 first">
            		<a href="/">Home</a>
                </span>
                <span class="active breadcrumb-1"><a href="/gallery">GALLERY</a></span>
                <?php if(isset($this->images[0]["album_title"])):?>
		        <span class="active">
		        	<?php echo $this->images[0]["album_title"]?>
		        </span>
		        <?php endif?>
            </div>
            <section id="content">     
            	<h1 class="page-title"><?php echo $this->displayElement("page_banner_title")?></h1> 
        			<div class="region region-content">
						<div id="block-views-news-archive-block" class="block block-views">		
							<div class="content">	
									<div class="view-content">
                                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
										<!-- Wrapper for slides -->
										<div class="carousel-inner" role="listbox">
											<?php if(isset($this->images)):?>
											<div class="item">
												<?php foreach($this->images as $image):?>
										      	<img src="/Data/Images/<?php echo $image["album_folder"]?>/<?php echo $image["dimensions"]?>_thumb/<?php echo $image["path"]?>">
										      	<?php endforeach?>
										    </div>
										    <?php endif?>
										    
										    <div class="item active">
										      	<img src="/Data/Images/<?php echo $image["album_folder"]?>/<?php echo $image["dimensions"]?>_thumb/<?php echo $image["path"]?>">
											</div>
										</div>
  										<!-- Controls -->
  										<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
  										</a>
  										<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    										<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    										<span class="sr-only">Next</span>
  										</a>
									</div>
								</div> 
							</div>
						</div>
					</div>
			</section>

    	<aside id="right">
        	<div class="region region-right">
    			<div id="block-menu-menu-archive-right-menu" class="block block-menu">
  					<div class="content">
  					<?php if(isset($this->albums)):?>
    					<ul class="menu">
    					<?php foreach($this->albums as $album):?>
                        	<li class="first leaf"><a href="/gallery/view?album_id=<?php echo $album["album_id"]?>"><?php echo $album["album_title"]?></a></li>
                       	<?php endforeach;?>
                       	</ul>
                    <?php endif?>
                    </div>
				</div>
			</div>
		</aside>
  </div>
</div>


